```{r}
library(rayshader)
library(sp)
library(raster)
library(scales)
```

```{r}
elevation1 = raster("D:\\ML\\3D-mountain\\N49E020.SRTMGL1.hgt\\N49E020.hgt")

height_shade(raster_to_matrix(elevation1)) %>%
  plot_map()
```
```{r}
zion_r = raster("LC09_L1TP_188025_20241203_20241203_02_T1_B4.TIF")
zion_g = raster("LC09_L1TP_188025_20241203_20241203_02_T1_B3.TIF")
zion_b = raster("LC09_L1TP_188025_20241203_20241203_02_T1_B2.TIF")

zion_rbg = stack(zion_r, zion_g, zion_b)
plotRGB(zion_rbg, scale=255^2)
```
```{r}
#gamma correction
zion_rbg_corrected = sqrt(stack(zion_r, zion_g, zion_b))
plotRGB(zion_rbg_corrected)
```
```{r}
crs(zion_r)
```
```{r}
#Our imagery data is given in UTM coordinates, while our elevation is in long/lat, to transform the elevation data from long/lat to UTM:

zion_elevation_utm = projectRaster(elevation1, crs = crs(zion_r), method = "bilinear")
crs(zion_elevation_utm)
```
```{r}
bottom_left = c(y=49.423344, x=20.388093)
top_right   = c(y=49.488794, x=20.702144)

extent_latlong = sp::SpatialPoints(rbind(bottom_left, top_right), proj4string=sp::CRS("+proj=longlat +ellps=WGS84 +datum=WGS84"))
extent_utm = sp::spTransform(extent_latlong, raster::crs(zion_elevation_utm))

e = raster::extent(extent_utm)
e
```
```{r}
zion_rgb_cropped = raster::crop(zion_rbg_corrected, e)
elevation_cropped = raster::crop(zion_elevation_utm, e)

names(zion_rgb_cropped) = c("r","g","b")

zion_r_cropped = rayshader::raster_to_matrix(zion_rgb_cropped$r)
zion_g_cropped = rayshader::raster_to_matrix(zion_rgb_cropped$g)
zion_b_cropped = rayshader::raster_to_matrix(zion_rgb_cropped$b)

zionel_matrix = rayshader::raster_to_matrix(elevation_cropped)

zion_rgb_array = array(0,dim=c(nrow(zion_r_cropped),ncol(zion_r_cropped),3))

zion_rgb_array[,,1] = zion_r_cropped/255 #Red layer
zion_rgb_array[,,2] = zion_g_cropped/255 #Blue layer
zion_rgb_array[,,3] = zion_b_cropped/255 #Green layer

zion_rgb_array = aperm(zion_rgb_array, c(2,1,3))

plot_map(zion_rgb_array)
```

